name: happypose_torch2
channels:
   - conda-forge
   - pytorch
   - nvidia
   - anaconda
   - defaults
dependencies:
  - pytorch-cuda==12.1
  - pip
  - pytorch
  - torchvision
  - geckodriver
  - firefox
  - opencv
  - pinocchio
  - torchtnt
  - pip:
    - torchnet
