name: happypose
channels:
   - conda-forge
   - pytorch
   - nvidia
dependencies:
  - pytorch-cuda==12.4
  - pip
  - pytorch
  - torchvision
  - geckodriver
  - firefox
  - opencv
  - pinocchio
  - torchtnt
  - pip:
    - torchnet
    - numpy<2
